name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      
    - name: Setup Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x

    - name: Setup Defold
      uses: dapetcu21/setup-defold@v3.0.2
      
    - name: Install Dependencies
      run: npm install
      
    - name: Generate lua w/ ts-defold
      run: npm run build

    - name: Build
      run: 'java -jar $BOB --root ./app --archive --platform js-web --bundle-output ./bundle --verbose resolve distclean build bundle'
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: bundle/tsd-template-yagames
    
